spring:
  application:
    name: user-account-service
  datasource:
    url: jdbc:aws-wrapper:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?wrapperPlugins=iam&iamRegion=${AWS_REGION:us-east-1}
    username: ${DB_USER:admin}
    password: ""
    driver-class-name: software.amazon.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 10000
      max-lifetime: 840000
  sql:
    init:
      mode: never
server:
  port: 8080
