apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tempo-west-nlb
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            region: us-west-2
  template:
    metadata:
      name: 'tempo-west-nlb-{{metadata.labels.region}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:<GITHUB_ORG>/multi-region-architecture.git
        targetRevision: main
        path: k8s/infra/tempo-west
        kustomize:
          patches:
            - target:
                kind: Service
                name: tempo-west-nlb
              patch: |-
                - op: add
                  path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-security-groups
                  value: "sg-0eeeee55555fffff6"
      destination:
        server: '{{server}}'
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
