apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-karpenter
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            region: us-east-1
        values:
          roleSuffix: ""
    - clusters:
        selector:
          matchLabels:
            region: us-west-2
        values:
          roleSuffix: "-us-west-2"
  template:
    metadata:
      name: 'karpenter-{{metadata.labels.region}}'
    spec:
      project: default
      source:
        chart: karpenter
        repoURL: public.ecr.aws/karpenter
        targetRevision: 1.9.0
        helm:
          valuesObject:
            settings:
              clusterName: multi-region-mall
              interruptionQueue: multi-region-mall-karpenter
            serviceAccount:
              name: karpenter
              annotations:
                eks.amazonaws.com/role-arn: 'arn:aws:iam::180294183052:role/multi-region-mall-karpenter-controller{{values.roleSuffix}}'
            replicas: 2
      destination:
        server: '{{server}}'
        namespace: karpenter
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
