apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-external-secrets
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            region: us-east-1
        values:
          awsRegion: us-east-1
    - clusters:
        selector:
          matchLabels:
            region: us-west-2
        values:
          awsRegion: us-west-2
  template:
    metadata:
      name: 'external-secrets-{{name}}'
    spec:
      project: default
      source:
        chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: 0.14.0
        helm:
          valuesObject:
            installCRDs: true
            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/multi-region-mall-external-secrets-{{values.awsRegion}}
            webhook:
              port: 9443
            certController:
              enabled: true
      destination:
        server: '{{server}}'
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
