apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clickhouse
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            region: us-east-1
    - clusters:
        selector:
          matchLabels:
            region: us-west-2
  template:
    metadata:
      name: 'clickhouse-{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Atom-oh/multi-region-architecture.git
        targetRevision: main
        path: k8s/infra/clickhouse
      destination:
        server: '{{server}}'
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
