apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-services
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'user-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Atom-oh/multi-region-architecture.git
        targetRevision: main
        path: k8s/services/user
      destination:
        server: '{{server}}'
        namespace: user-services
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
