apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-karpenter
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: region
              operator: Exists
  template:
    metadata:
      name: 'karpenter-{{metadata.labels.region}}'
    spec:
      project: default
      source:
        chart: karpenter
        repoURL: public.ecr.aws/karpenter
        targetRevision: 1.9.0
        helm:
          valuesObject:
            settings:
              clusterName: multi-region-mall
              interruptionQueue: multi-region-mall-karpenter
            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::180294183052:role/multi-region-mall-karpenter-controller-{{metadata.labels.region}}
            replicas: 2
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
