apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-services
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: region
              operator: Exists
  template:
    metadata:
      name: 'user-{{metadata.labels.region}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Atom-oh/multi-region-architecture.git
        targetRevision: main
        path: 'k8s/overlays/{{metadata.labels.region}}/user'
      destination:
        server: '{{server}}'
        namespace: user-services
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
