apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fulfillment
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            region: us-east-1
        values:
          overlayPath: us-east-1
    - clusters:
        selector:
          matchLabels:
            region: us-west-2
        values:
          overlayPath: us-west-2
  template:
    metadata:
      name: 'fulfillment-{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:<GITHUB_ORG>/multi-region-architecture.git
        targetRevision: main
        path: 'k8s/overlays/{{values.overlayPath}}/fulfillment'
      destination:
        server: '{{server}}'
        namespace: fulfillment
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
