apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appset-core.yaml
  - appset-user.yaml
  - appset-fulfillment.yaml
  - appset-business.yaml
  - appset-platform.yaml
  - appset-infra.yaml
  - appset-tempo.yaml
  - appset-storageclass.yaml
  - appset-helm-karpenter.yaml
  - appset-helm-external-secrets.yaml
  - appset-helm-prometheus.yaml
  - appset-helm-prometheus-west.yaml
  - appset-helm-prometheus-korea.yaml
  - appset-helm-otel-collector.yaml
  - appset-helm-alb-controller.yaml
  - appset-grafana-nlb.yaml
  - appset-prometheus-west-nlb.yaml
  - appset-tempo-west-nlb.yaml
  - appset-helm-clickhouse-operator.yaml
  - appset-clickhouse.yaml
