apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - root-app.yaml
  - appset-core.yaml
  - appset-user.yaml
  - appset-fulfillment.yaml
  - appset-business.yaml
  - appset-platform.yaml
  - appset-infra.yaml
  - appset-helm-karpenter.yaml
  - appset-helm-external-secrets.yaml
  - appset-helm-prometheus.yaml
  - appset-helm-fluent-bit.yaml
  - appset-helm-otel-collector.yaml
