apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../services/platform
  - ../../../services/platform/synthetic-monitor

patches:
  - target:
      kind: TargetGroupBinding
      name: api-gateway-tgb
    patch: |-
      - op: replace
        path: /spec/targetGroupARN
        value: "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/production-api-tg-us-east-1/xxxxxxxxxxxxxxxx"
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REGION_ROLE
          value: "PRIMARY"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AWS_REGION
          value: "us-east-1"

commonLabels:
  region: us-east-1
  region-role: primary
