apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../services/platform
  - ../../../services/platform/synthetic-monitor

patches:
  - target:
      kind: TargetGroupBinding
      name: api-gateway-tgb
    patch: |-
      - op: replace
        path: /spec/targetGroupARN
        value: "arn:aws:elasticloadbalancing:ap-northeast-2:180294183052:targetgroup/prod-wtg-apne2-az-a/56b6d65d7ffe61ba"
  - target:
      kind: CronJob
      name: synthetic-monitor
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/2
        value:
          name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.platform.svc.cluster.local:4317"
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/3
        value:
          name: ORIGIN_REGION
          value: "ap-northeast-2"
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REGION_ROLE
          value: "SECONDARY"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AWS_REGION
          value: "ap-northeast-2"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AVAILABILITY_ZONE
          value: "ap-northeast-2a"

commonLabels:
  region: ap-northeast-2
  region-role: secondary
  availability-zone: ap-northeast-2a
