apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-alb-controller
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-a
        values:
          roleArn: "arn:aws:iam::123456789012:role/production-alb-controller-apne2-az-a"
          vpcId: vpc-0e1b8458f46f9f81d
          awsRegion: ap-northeast-2
          clusterName: mall-apne2-az-a
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-c
        values:
          roleArn: "arn:aws:iam::123456789012:role/production-alb-controller-apne2-az-c"
          vpcId: vpc-0e1b8458f46f9f81d
          awsRegion: ap-northeast-2
          clusterName: mall-apne2-az-c
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-mgmt
        values:
          roleArn: "arn:aws:iam::123456789012:role/mall-apne2-mgmt-alb-controller-apne2-mgmt"
          vpcId: vpc-0e1b8458f46f9f81d
          awsRegion: ap-northeast-2
          clusterName: mall-apne2-mgmt
  template:
    metadata:
      name: 'alb-controller-{{name}}'
    spec:
      project: default
      source:
        chart: aws-load-balancer-controller
        repoURL: https://aws.github.io/eks-charts
        targetRevision: 3.1.0
        helm:
          valuesObject:
            clusterName: '{{values.clusterName}}'
            serviceAccount:
              name: aws-load-balancer-controller
              annotations:
                eks.amazonaws.com/role-arn: '{{values.roleArn}}'
            region: '{{values.awsRegion}}'
            vpcId: '{{values.vpcId}}'
            tolerations:
              - key: node-role
                value: system-critical
                effect: NoSchedule
            nodeSelector:
              role: system
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
