apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-karpenter-crds
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-a
        values:
          karpenterPath: k8s/infra/karpenter-apne2-az-a
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-c
        values:
          karpenterPath: k8s/infra/karpenter-apne2-az-c
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-mgmt
        values:
          karpenterPath: k8s/infra/karpenter-apne2-mgmt
  template:
    metadata:
      name: 'infra-karpenter-crds-{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:<GITHUB_ORG>/multi-region-architecture.git
        targetRevision: main
        path: '{{values.karpenterPath}}'
      destination:
        server: '{{server}}'
        namespace: karpenter
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
