apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-services
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-a
        values:
          overlayPath: ap-northeast-2-az-a
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-c
        values:
          overlayPath: ap-northeast-2-az-c
  template:
    metadata:
      name: 'user-{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Atom-oh/multi-region-architecture.git
        targetRevision: main
        path: 'k8s/overlays/{{values.overlayPath}}/user'
        kustomize:
          images:
            - '<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/user-account={{metadata.annotations.ecr-registry}}/shopping-mall/user-account'
            - '<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/user-profile={{metadata.annotations.ecr-registry}}/shopping-mall/user-profile'
            - '<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/review={{metadata.annotations.ecr-registry}}/shopping-mall/review'
            - '<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/wishlist={{metadata.annotations.ecr-registry}}/shopping-mall/wishlist'
      destination:
        server: '{{server}}'
        namespace: user-services
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
