apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storageclass
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-a
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-c
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-mgmt
  template:
    metadata:
      name: 'storageclass-{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Atom-oh/multi-region-architecture.git
        targetRevision: main
        path: k8s/infra/storageclass
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
