apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-a
        values:
          overlayPath: ap-northeast-2-az-a
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-c
        values:
          overlayPath: ap-northeast-2-az-c
  template:
    metadata:
      name: 'platform-{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Atom-oh/multi-region-architecture.git
        targetRevision: main
        path: 'k8s/overlays/{{values.overlayPath}}/platform'
        kustomize:
          images:
            - '180294183052.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/api-gateway={{metadata.annotations.ecr-registry}}/shopping-mall/api-gateway'
            - '180294183052.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/event-bus={{metadata.annotations.ecr-registry}}/shopping-mall/event-bus'
            - '180294183052.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/analytics={{metadata.annotations.ecr-registry}}/shopping-mall/analytics'
            - '180294183052.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/synthetic-monitor={{metadata.annotations.ecr-registry}}/shopping-mall/synthetic-monitor'
      destination:
        server: '{{server}}'
        namespace: platform
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
