apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fulfillment
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-a
        values:
          overlayPath: ap-northeast-2-az-a
    - clusters:
        selector:
          matchLabels:
            cluster-name: mall-apne2-az-c
        values:
          overlayPath: ap-northeast-2-az-c
  template:
    metadata:
      name: 'fulfillment-{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Atom-oh/multi-region-architecture.git
        targetRevision: main
        path: 'k8s/overlays/{{values.overlayPath}}/fulfillment'
        kustomize:
          images:
            - '123456789012.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/shipping={{metadata.annotations.ecr-registry}}/shopping-mall/shipping'
            - '123456789012.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/warehouse={{metadata.annotations.ecr-registry}}/shopping-mall/warehouse'
            - '123456789012.dkr.ecr.us-east-1.amazonaws.com/shopping-mall/returns={{metadata.annotations.ecr-registry}}/shopping-mall/returns'
      destination:
        server: '{{server}}'
        namespace: fulfillment
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
