apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appset-core.yaml
  - appset-user.yaml
  - appset-fulfillment.yaml
  - appset-business.yaml
  - appset-platform.yaml
  - appset-infra.yaml
  - appset-tempo.yaml
  - appset-storageclass.yaml
  - appset-clickhouse.yaml
  - appset-grafana-dashboards.yaml
  - appset-helm-karpenter.yaml
  - appset-helm-external-secrets.yaml
  - appset-helm-alb-controller.yaml
  - appset-helm-clickhouse-operator.yaml
  - appset-helm-otel-collector.yaml
  - appset-helm-prometheus-mgmt.yaml
  - appset-helm-prometheus-workload.yaml
  - appset-helm-actions-runner-controller.yaml
  - appset-helm-runner-x86.yaml
  - appset-helm-runner-arm.yaml
  - appset-helm-runner-x86-aws-fsi-demo.yaml
  - appset-helm-runner-arm-aws-fsi-demo.yaml
  - appset-helm-runner-x86-awsops.yaml
  - appset-helm-runner-arm-awsops.yaml
  - appset-helm-runner-x86-cc-on-bedrock.yaml
  - appset-helm-runner-arm-cc-on-bedrock.yaml
  - appset-helm-runner-x86-ttobak.yaml
  - appset-helm-runner-arm-ttobak.yaml
  - appset-grafana-nlb.yaml
