apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-nlb.yaml
  - prometheus-west-nlb.yaml

patches:
  - target:
      kind: ConfigMap
      name: grafana-dashboard-karpenter
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          grafana_folder: "Basic"

configMapGenerator:
  - name: grafana-dashboard-synthetic-monitor
    namespace: monitoring
    files:
      - dashboards/synthetic-monitor.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-karpenter
    namespace: monitoring
    files:
      - dashboards/karpenter.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-service-health
    namespace: monitoring
    files:
      - dashboards/service-health.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-multi-region-comparison
    namespace: monitoring
    files:
      - dashboards/multi-region-comparison.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-infrastructure-nodepools
    namespace: monitoring
    files:
      - dashboards/infrastructure-nodepools.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
