#!/bin/bash
# ============================================================================
# Multi-Region Shopping Mall - OpenSearch Seed Data
# Creates product search index with nori (Korean) analyzer + bulk index 1000 products
# Reads product data from products-1000.json (generated by crawl-products.py)
# ============================================================================

set -euo pipefail

OS_ENDPOINT="${OPENSEARCH_ENDPOINT:-https://localhost:9200}"
OS_USER="${OPENSEARCH_USER:-admin}"
OS_PASS="${OPENSEARCH_PASS:-<YOUR_PASSWORD>}"
CURL="curl -s -u ${OS_USER}:${OS_PASS} --insecure"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== OpenSearch Seed Data ==="
echo "Endpoint: ${OS_ENDPOINT}"

# ── Delete existing index ───────────────────────────────────────────────────
echo "Deleting existing product index..."
$CURL -X DELETE "${OS_ENDPOINT}/products" 2>/dev/null || true

# ── Create index with nori analyzer ─────────────────────────────────────────
echo "Creating product index with nori analyzer..."
$CURL -X PUT "${OS_ENDPOINT}/products" -H 'Content-Type: application/json' -d '{
  "settings": {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1
    },
    "analysis": {
      "analyzer": {
        "korean": {
          "type": "custom",
          "tokenizer": "nori_tokenizer",
          "filter": ["nori_readingform", "lowercase", "nori_part_of_speech_basic"]
        },
        "korean_search": {
          "type": "custom",
          "tokenizer": "nori_tokenizer",
          "filter": ["nori_readingform", "lowercase", "synonym_filter"]
        }
      },
      "filter": {
        "nori_part_of_speech_basic": {
          "type": "nori_part_of_speech",
          "stoptags": ["E", "IC", "J", "MAG", "MAJ", "MM", "SP", "SSC", "SSO", "SC", "SE", "XPN", "XSA", "XSN", "XSV", "UNA", "NA", "VSV"]
        },
        "synonym_filter": {
          "type": "synonym",
          "synonyms": [
            "노트북,랩탑,laptop",
            "핸드폰,스마트폰,휴대폰,phone",
            "냉장고,refrigerator,fridge",
            "세탁기,washing machine",
            "에어컨,에어컨디셔너,air conditioner",
            "청소기,vacuum cleaner",
            "이어폰,이어버드,earphone,earbuds",
            "헤드폰,헤드셋,headphone",
            "신발,운동화,슈즈,shoes,sneakers",
            "가방,백,bag",
            "기저귀,diaper,nappy",
            "분유,formula,baby milk",
            "유모차,stroller,buggy",
            "강아지,개,dog,puppy",
            "고양이,cat,kitty",
            "소파,couch,sofa",
            "침대,bed",
            "책상,desk",
            "의자,chair"
          ]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "productId":   { "type": "keyword" },
      "name":        { "type": "text", "analyzer": "korean", "search_analyzer": "korean_search", "fields": { "keyword": { "type": "keyword" } } },
      "brand":       { "type": "text", "analyzer": "korean", "fields": { "keyword": { "type": "keyword" } } },
      "category":    { "type": "keyword" },
      "categoryName":{ "type": "text", "analyzer": "korean", "fields": { "keyword": { "type": "keyword" } } },
      "description": { "type": "text", "analyzer": "korean" },
      "price":       { "type": "long" },
      "salePrice":   { "type": "long" },
      "discount":    { "type": "integer" },
      "rating":      { "type": "float" },
      "reviewCount": { "type": "integer" },
      "tags":        { "type": "keyword" },
      "status":      { "type": "keyword" },
      "stock":       { "type": "integer" },
      "origin":      { "type": "keyword" },
      "createdAt":   { "type": "date" }
    }
  }
}'
echo ""

# ── Bulk index products from products-1000.json ────────────────────────────
echo "Generating bulk data from products-1000.json..."

BULK_FILE=$(mktemp)

python3 -c "
import json, sys, os
products = json.load(open(os.path.join('${SCRIPT_DIR}', 'products-1000.json')))
for p in products:
    action = json.dumps({'index': {'_index': 'products', '_id': p['productId']}})
    doc = json.dumps({
        'productId': p['productId'],
        'name': p['name'],
        'brand': p['brand'],
        'category': p['category']['slug'],
        'categoryName': p['category']['name'],
        'description': p['description'],
        'price': p['price'],
        'salePrice': p.get('salePrice') or 0,
        'discount': p.get('discount', 0),
        'rating': p['rating'],
        'reviewCount': p['reviewCount'],
        'tags': p['tags'],
        'status': p['status'],
        'stock': p['stock']['available'],
        'origin': p['attributes'].get('origin', '한국'),
        'createdAt': p['createdAt']
    }, ensure_ascii=False)
    print(action)
    print(doc)
print(f'Generated {len(products)} bulk entries', file=sys.stderr)
" > "$BULK_FILE" 2>&1

IDX=$(python3 -c "import json; print(len(json.load(open('${SCRIPT_DIR}/products-1000.json'))))")
echo "Bulk indexing ${IDX} products..."
RESPONSE=$($CURL -X POST "${OS_ENDPOINT}/_bulk" -H 'Content-Type: application/x-ndjson' --data-binary "@${BULK_FILE}")
ERRORS=$(echo "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('errors',True))" 2>/dev/null || echo "unknown")

if [ "$ERRORS" = "False" ]; then
  echo "Bulk indexing complete: ${IDX} products indexed successfully"
else
  echo "Bulk indexing completed with some errors. Check response."
  echo "$RESPONSE" | python3 -c "
import sys, json
d = json.load(sys.stdin)
errs = [i for i in d.get('items',[]) if 'error' in i.get('index',{})]
print(f'Errors: {len(errs)}')
for e in errs[:5]:
    print(f'  {e[\"index\"][\"_id\"]}: {e[\"index\"][\"error\"][\"reason\"]}')
" 2>/dev/null || true
fi

rm -f "$BULK_FILE"

# ── Create notification index ───────────────────────────────────────────────
echo ""
echo "Creating notification-logs index..."
$CURL -X DELETE "${OS_ENDPOINT}/notification-logs" 2>/dev/null || true
$CURL -X PUT "${OS_ENDPOINT}/notification-logs" -H 'Content-Type: application/json' -d '{
  "settings": { "number_of_shards": 2, "number_of_replicas": 1 },
  "mappings": {
    "properties": {
      "userId":    { "type": "keyword" },
      "type":      { "type": "keyword" },
      "channel":   { "type": "keyword" },
      "title":     { "type": "text", "analyzer": "korean" },
      "status":    { "type": "keyword" },
      "sentAt":    { "type": "date" },
      "readAt":    { "type": "date" }
    }
  }
}'
echo ""

# ── Create order-events index ───────────────────────────────────────────────
echo "Creating order-events index..."
$CURL -X DELETE "${OS_ENDPOINT}/order-events" 2>/dev/null || true
$CURL -X PUT "${OS_ENDPOINT}/order-events" -H 'Content-Type: application/json' -d '{
  "settings": { "number_of_shards": 3, "number_of_replicas": 1 },
  "mappings": {
    "properties": {
      "orderId":   { "type": "keyword" },
      "userId":    { "type": "keyword" },
      "eventType": { "type": "keyword" },
      "status":    { "type": "keyword" },
      "amount":    { "type": "long" },
      "timestamp": { "type": "date" }
    }
  }
}'
echo ""

# ── Verify ──────────────────────────────────────────────────────────────────
echo ""
echo "=== Verification ==="
echo -n "Products count: "
$CURL "${OS_ENDPOINT}/products/_count" | python3 -c "import sys,json; print(json.load(sys.stdin).get('count',0))" 2>/dev/null || echo "?"

echo -n "Sample search for '삼성': "
$CURL -X POST "${OS_ENDPOINT}/products/_search" -H 'Content-Type: application/json' -d '{
  "query": { "match": { "name": "삼성" } },
  "size": 0
}' | python3 -c "import sys,json; print(json.load(sys.stdin).get('hits',{}).get('total',{}).get('value',0), 'hits')" 2>/dev/null || echo "?"

echo ""
echo "OpenSearch seed complete!"
