apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shipping-secrets
  namespace: fulfillment
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: shipping-secrets
    creationPolicy: Owner
  data:
    - secretKey: DOCUMENTDB_HOST
      remoteRef:
        key: mall/fulfillment/documentdb
        property: host
    - secretKey: DOCUMENTDB_PORT
      remoteRef:
        key: mall/fulfillment/documentdb
        property: port
    - secretKey: DOCUMENTDB_USER
      remoteRef:
        key: mall/fulfillment/documentdb
        property: username
    - secretKey: DOCUMENTDB_PASSWORD
      remoteRef:
        key: mall/fulfillment/documentdb
        property: password
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: mall/shared/msk
        property: brokers
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: warehouse-secrets
  namespace: fulfillment
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: warehouse-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: mall/fulfillment/aurora
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: mall/fulfillment/aurora
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: mall/fulfillment/aurora
        property: database
    - secretKey: DB_USER
      remoteRef:
        key: mall/fulfillment/aurora
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mall/fulfillment/aurora
        property: password
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: mall/shared/msk
        property: brokers
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: returns-secrets
  namespace: fulfillment
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: returns-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: mall/fulfillment/aurora
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: mall/fulfillment/aurora
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: mall/fulfillment/aurora
        property: database
    - secretKey: DB_USER
      remoteRef:
        key: mall/fulfillment/aurora
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mall/fulfillment/aurora
        property: password
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: mall/shared/msk
        property: brokers
