apiVersion: v1
kind: Namespace
metadata:
  name: core-services
  labels:
    app.kubernetes.io/part-of: shopping-mall
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-services
  labels:
    app.kubernetes.io/part-of: shopping-mall
---
apiVersion: v1
kind: Namespace
metadata:
  name: fulfillment
  labels:
    app.kubernetes.io/part-of: shopping-mall
---
apiVersion: v1
kind: Namespace
metadata:
  name: business-services
  labels:
    app.kubernetes.io/part-of: shopping-mall
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/part-of: shopping-mall
